--- 
before_script: 
  - "phpenv config-rm xdebug.ini || echo 'No xdebug config.'"
  - "composer global require friendsofphp/php-cs-fixer"
cache: 
  directories: 
    - $HOME/.php-cs-fixer
dist: trusty
ignore: 
  - /docs/*
  - /js/*
  - /css/critical.min.css
language: php
matrix: 
  fast_finish: true
  include: 
    - 
      dist: precise
      php: "5.2"
    - 
      php: "5.6"
    - 
      php: "7.0"
    - 
      php: "7.3"
    - 
      php: nightly
script: 
  - "find -L . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l"
  - "find -L . -name '*.php' -print0 | php php-cs-fixer fix --diff"
sudo: false
