language: php

php:
  - 5.6
    env: cs=true
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.php-cs-fixer

install:
 - composer require --dev dotsunited/php-cs-fixer-config 

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"

script:
  - if [ "$cs" = "true" ]; then vendor/bin/php-cs-fixer fix --verbose --diff --dry-run; fi
  - vendor/bin/phpunit -v --coverage-text
