--- 
before_script: 
  - "phpenv config-rm xdebug.ini || echo 'No xdebug config.'"
  - "export PHPCS_DIR=/tmp/phpcs"
  - "export WPCS_DIR=/tmp/wpcs"
  - "export PHPCOMPAT_DIR=/tmp/phpcompatibility"
  - "if [[ \"$SNIFF\" == \"1\" ]]; then git clone -b master --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR; fi"
  - "if [[ \"$SNIFF\" == \"1\" ]]; then git clone -b 0.14.1 --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $WPCS_DIR; fi"
  - "if [[ \"$SNIFF\" == \"1\" ]]; then git clone -b master --depth 1 https://github.com/wimg/PHPCompatibility.git $PHPCOMPAT_DIR; fi"
  - "if [[ \"$SNIFF\" == \"1\" ]]; then $PHPCS_DIR/bin/phpcs --config-set installed_paths $WPCS_DIR,$PHPCOMPAT_DIR; fi"
  - "if [[ \"$SNIFF\" == \"1\" ]]; then phpenv rehash; fi"
  - "if [[ \"$SNIFF\" == \"1\" ]]; then npm install -g jscs; fi"
  - "if [[ \"$SNIFF\" == \"1\" ]]; then npm install -g jshint; fi"
  - "if [[ \"$SNIFF\" == \"1\" ]]; then wget https://develop.svn.wordpress.org/trunk/.jshintrc; fi"
dist: trusty
ignore: 
  - /docs/*
  - /js/keyboard.js
  - /css/critical.min.css
  - /js/buttons.min.js
language: php
matrix: 
  allow_failures: 
    - 
      php: nightly
  fast_finish: true
  include: 
    - 
      dist: precise
      php: "5.2"
    - 
      env: SNIFF=1
      php: "5.6"
    - 
      php: "7.0"
    - 
      env: SNIFF=1
      php: "7.3"
    - 
      php: nightly
notifications: 
  email: false
script: 
  - "find -L . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l"
  - "if [[ \"$SNIFF\" == \"1\" ]]; then jshint .; fi"
  - "if [[ \"$SNIFF\" == \"1\" ]]; then jscs .; fi"
  - "if [[ \"$SNIFF\" == \"1\" ]]; then $PHPCS_DIR/bin/phpcs --runtime-set ignore_warnings_on_exit 1; fi"
sudo: false
